# Generated by Django 5.0.7 on 2024-07-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Use it in templatetag for displaying menu",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, help_text="Named url from urls.py", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "menu",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.CharField(blank=True, max_length=100)),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Named url from urls.py",
                        max_length=255,
                        verbose_name="Named URL",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "menu items",
            },
        ),
    ]
